name: "Test"

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Upload to Release"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: README.md
          tag: ${{ github.ref }}
          overwrite: false

      - name: "Test VirusTotal Action"
        uses: cssnr/virustotal-action@outputs
        id: vt
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vt_api_key: ${{ secrets.VT_API_KEY }}

      - name: "Echo Results"
        run: echo ${{ steps.vt.outputs.results }}
